---
# front end tls cert data

apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls_crt }}
  tls.key: {{ .Values.ingress.tls_key }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls_secret_name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls

---
